function dav = davisdat(filename)
    % Loads some of the data generated by Jason Moore into a structure
    % called DAT.
    
    dat = load(['data/measurements/' filename]);

    Fs = dat.NISampleRate; Fs = double(Fs);

    v = dat.ForwardSpeed; 

    y(:,1) = dat.RollAngle;
    y(:,2) = dat.SteerAngle;
    f      = dat.PullForce;
    Tdelta = dat.SteerTorque;
    N = size(y,1);

    t = (0:N-1)'./Fs;
    % Output
    dav.filename = filename;
    dav.Tdelta = Tdelta;
    dav.Fs = Fs;
    dav.v = mean(v);
    dav.t = t; 
    dav.y = y;
    dav.N = N;
    dav.w = f;
    
    switch filename;   
        case '00184.mat';
            dav.w = -dav.w;
    end
    
end

